# Generated by Django 5.1.2 on 2024-11-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_atividade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('progresso', 'Progresso'), ('concluida', 'Concluída')], default='pendente', max_length=20),
        ),
    ]
